// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: world.proto

package msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WorldClient is the client API for World service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorldClient interface {
	Broadcast(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type worldClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldClient(cc grpc.ClientConnInterface) WorldClient {
	return &worldClient{cc}
}

func (c *worldClient) Broadcast(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/msg.World/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorldServer is the server API for World service.
// All implementations must embed UnimplementedWorldServer
// for forward compatibility
type WorldServer interface {
	Broadcast(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedWorldServer()
}

// UnimplementedWorldServer must be embedded to have forward compatible implementations.
type UnimplementedWorldServer struct {
}

func (UnimplementedWorldServer) Broadcast(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedWorldServer) mustEmbedUnimplementedWorldServer() {}

// UnsafeWorldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldServer will
// result in compilation errors.
type UnsafeWorldServer interface {
	mustEmbedUnimplementedWorldServer()
}

func RegisterWorldServer(s grpc.ServiceRegistrar, srv WorldServer) {
	s.RegisterService(&World_ServiceDesc, srv)
}

func _World_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.World/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).Broadcast(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// World_ServiceDesc is the grpc.ServiceDesc for World service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var World_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.World",
	HandlerType: (*WorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _World_Broadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "world.proto",
}
